[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  external_node_modules = ["node-fetch"]
  node_bundler = "esbuild"

[dev]
  port = 3000
  publish = "."
  functions = "netlify/functions"